### ISSUE TITLE
US-62: Refactoring application

### ISSUE THREAD

**Issue by willayy** [0-Gixty-0/Grupp-11-OOPP#104]
As a developer i want to refactor application

### Because
The application (Or rather Main) class is in its current state a rushed product with a lot of code smelles. If we dont fix this the application code will be hard to maintain and unreadable. 

### Tasks
- [ ] Refactor movement.
- [ ] Refactor Initialization of model objects into its own class.
- [ ] Make the Application into a package.
- [ ] Make Main class run the application (Main class should be very few lines).
- [ ] Make Application module SOLID

### Acceptance criteria
For this US to be considered done the application package should be SOLID, with extra focus on extendibility and modularity within the boundaries of the project ofcourse. Application should also make sure there are no dependencies between MVC modules.
