### ISSUE TITLE
US-65: Implement UEntityMatrixDecoder

### ISSUE THREAD

**Issue by adamkvarnsund** [0-Gixty-0/Grupp-11-OOPP#108]
As a developer I want the entity matrix to be represented by integers corresponding to their type instead of objects

### Because
This makes the codebase more modular because it makes it possible for the view to handle all objects with its own representation

### Tasks

- [x] Create a class with name UEntityMatrixDecoder
- [x] Implement a way to map entities to integers
- [x] Implement a getter function for each entities ID
- [x] Implement a function that decodes the object matrix into a integer matrix
- [x] Make tests for the class
- [x] Add JavaDoc and documentation in README

### Acceptance criteria
The object matrix that is sent into the decoder is fully converted to a integer matrix that the view can comprehend

**Comment by willayy** [comment]
close this issue if its finished @adamkvarnsund
