### ISSUE TITLE
US-67: Implement Entity Builder For Player And Enemy

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#110]
### US-67:
As a developer I want to be able to create the model representation of a player and an enemy more easily so that the code is easier to understand and use

This user story is about implementing the builder design pattern for creating a model representation of a player and an enemy. I think that this design pattern is fitting because it solves the issue of long constructor calls to Ship and cleans up the code by not having to make an entity and a body over and over manually for each representation

### Tasks:

- [x] Create an interface IEntityBuilder
- [x] Create a director class EntityDirector
- [x] Create a concrete builder class ShipBuilder

### Acceptance Criteria

- [x] It is possible to create the model representation of the player through the director
- [x] It is possible to create the model representation of the enemy through the director
