### ISSUE TITLE
US-68: Implement Method For Creating New Enemy Wave

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#114]
### US-68:
As a user I want there to be new enemies on each wave to make the game endlessly playable

This user story is about creating a method for creating a new enemy wave based on some wave difficulty parameter so that when the player destroys all enemies in a wave a new one is created.

### Tasks:

- [ ] Implement method createNewWave() in application

### Acceptance Criteria:
- [ ] Method createNewWave should create enemies of different levels based on some wave difficulty parameter
- [ ] The method createNewWave returns a list of enemies
