### ISSUE TITLE
US-70: Implement Entity Matrix Generator Utility Class

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#124]
### US-70:
As a developer I want entities in the model to be represented in a matrix so that collision detection between entities is easier to implement.

This user story is about creating an entity matrix similar to that of the terrain matrix. This is then used by the collision detection and the encoder for the view.

### Tasks:

- [x] Create utility class UEntityMatrixGenerator
- [x] Create method for generating an entity matrix from a list of entities

### Acceptance Criteria:

- [x] The method places entity objects in the matrix in the correct position
- [x] The entity matrix has the same size as the map
