### ISSUE TITLE
US-71: Implement AI Movement For Enemies

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#129]
### US-71:
As a player I want the enemies in the game to move around so that the enemies are more challenging

This user story is about implementing some form of AI controlled movement for enemies in the game.

### Tasks:

- [x] Create class AICommander
- [x] Create methods for moving enemies through some algorithm
- [x] Create method for moving enemies closer to the player if in "sight"

### Acceptance Criteria:

- [x] ~~Enemies move their position each game tick~~
- [x] Enemies cannot move through walls
- [x] Enemies cannot get "stuck" // Move in weird ways
- [x] Enemies move towards the player if close enough
