### ISSUE TITLE
US-72: Implement Drawing EntityMatrix In View

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#130]
### US-72
As a player I want to see enemies in the game so that the game is interesting

This user story is about implementing the application connection to the EntityMatrix and drawing the objects in that matrix to the view.

### Tasks:

- [x] Implement method for encoding EntityMatrix
- [x] Implement method for sending EntityMatrix to view

### Acceptance Criteria:

- [x] Entities in the model can be seen in the frame

**Comment by willayy** [comment]
This functionality exists from #94
