### ISSUE TITLE
US-73: Implement AI Shooting For Enemies

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#131]
### US-73:
As a player I want the enemies in the game to fire back at me so that the game is more interesting to play.

This user story is about implementing AI behavior in enemies for shooting at the player.

### Tasks:

- [ ] Extend AICommander with methods for shooting at the player

### Acceptance Criteria:

- [ ] Enemies shoot at the player when they are in range
- [ ] Enemies fire projectiles in the direction of the player

**Comment by willayy** [comment]
This already exists dumdum💋🍻
