### ISSUE TITLE
US-75: Implement decoding for pressed arrows in keyboardinterpretor

### ISSUE THREAD

**Issue by DuchessMuhr** [0-Gixty-0/Grupp-11-OOPP#133]
As a developer I want to implement a decoding method for arrows to directon in keyboardinterpretor

### Because: 
I want a method that can translate pressed down arrows to a direction 0-7 that the shots that i am firing will go!

### Tasks:

- [ ] Implement arrowsToDir in KeyboardInterpretor

###Acceptance criteria:

- [ ] The multiple arrows pressed down will result in diagonals or no direction at all (-1) if they are opposite
- [ ] The method will work for all 8 directions and pass the tests
