### ISSUE TITLE
US-77: Fixing SOLID principle violations in controller

### ISSUE THREAD

**Issue by willayy** [0-Gixty-0/Grupp-11-OOPP#139]
As a developer I want the controller module to not violate the SOLID principles.

### Because
it makes code hard to maintain.

### Tasks
- [x] Use AControllerInterpretor interface instead of relying on concrete implementation KeyboardInterpretor, right the client cant use the abstraction which breaks teh DIP.
- [x] KeyboardInterpretor can be extended without breaking the ISP. Right now, if you where to add a method to for moving with IJKL aswell as WASD the class would rely on code it doesn't use.
- [x] Coupling between controller package and client is going to be unnecessarily high, if you make the Interpretor classes use a GlobalKeyListner the controller package would get higher cohesion and lower coupling. Right now the client has to get the input and then interpret it through two different objects.

### Acceptance criteria
The controller package should follow the SOLID principles and all tasks should be finished.
