### ISSUE TITLE
US-79: Implement dynamic map dimensions into MapGenerators

### ISSUE THREAD

**Issue by adamkvarnsund** [0-Gixty-0/Grupp-11-OOPP#143]
As a user I want the size of the map to be any rectangular size

### Because
I want the map generators to be able to generate maps with any dimensions, with custom width and height

### Tasks

- [ ] Implement mapWidth and mapHeight into BasicWorldGenerator
- [ ] Implement mapWidth and mapHeight into BasicMapGenerator
- [ ] Implement mapWidth and mapHeight into AdvancedMapGenerator
- [ ] Implement mapWidth and mapHeight into IMapGenerator
- [ ] Implement mapWidth and mapHeight into IWorldGenerator
- [ ] Implement mapWidth and mapHeight into Map

### Acceptance criteria
Every kind of map should be able to be created with custom width and height size and generate terrain accordingly. Also no class should use the side variable to create a matrix.
