### ISSUE TITLE
US-80: Renaming CommanbableEntity methods.

### ISSUE THREAD

**Issue by willayy** [0-Gixty-0/Grupp-11-OOPP#144]
As a developer I want to rename the moveCommand() and other similiar methods in the CommandableEntity class.

### Because
something like moveIfPossible() is more correct if you consider the methods contract (This was suggested by Niclas)

### Tasks
- [x] Rename moveCommand() to moveIfPossible()
- [x] Rename interactCommand() to interactIfPossible()
- [x] Rename attackCommand() to attackIfPossible()

### Acceptance criteria
Methods mentioned are renamed.
