### ISSUE TITLE
US-90: Implement AI Firing Of Weapons In AICommandable

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#187]
### US-85
As a player I want the enemies in the game to fire at me to make the game more engaging

Implementing methods in AICommandable to allow enemies to fire correctly towards the player.

### Tasks

- [x] Implement method for enemies to fire at player
- [x] Implement logic so that only enemies within range fire at the player
- [x] Implement logic so that enemies fire in the correct direction of the player
- [x] Integrate use of method in application

### Acceptance Criteria

- [x] Enemies within firing range of player fire at the player
- [x] Enemies fire in the correct direction facing the player

**Comment by willayy** [comment]
This looks a lot like US-73, this one or 73 should be closed.

**Comment by willayy** [comment]
US-85 already exists aswell so it needs to be renamed
