### ISSUE TITLE
US-89: Adding a small menu to the view

### ISSUE THREAD

**Issue by willayy** [0-Gixty-0/Grupp-11-OOPP#188]
As a user I would like to control when the game starts through a menu

### Because
Its confusing when the game starts immediately

### Tasks
- [ ] Make the view open for extension (specifically make it possible to add other views such as menus)
- [ ] Add a simple main menu
- [ ] Add a simple game over screen

### Acceptance criteria
This us is done when its easy to add new views to the application and the other components described in the tasks exists.
