### ISSUE TITLE
US-94: Implementing combat into the game

### ISSUE THREAD

**Issue by willayy** [0-Gixty-0/Grupp-11-OOPP#197]
As a user I want to be able to combat enemies.

### Because
It makes the game more interesting.

### Task

- [x] Projectiles cause damage to the player when the player is hit.
- [x] Projectiles cause damage to the enemies when the enemies are hit.
- [x] Projectiles are rendered on the screen.

### Acceptance criteria
When this US is finished the game should be playable according to our mvp.
