### ISSUE TITLE
US-95: Create factory for projectiles

### ISSUE THREAD

**Issue by adamkvarnsund** [0-Gixty-0/Grupp-11-OOPP#199]
As a user developer I want projectiles to be created through a factory

### Because
This design pattern lowers the coupling of the code which is a good practice when following object oriented design

### Tasks

- [x] Create class ProjectileFactory
- [x] Implement method for creating BasicCannonBall
- [x] Create tests for factory
- [x] Update UML diagram
- [x] Document code with Javadoc and in READme

### Acceptance criteria
The creation of projectiles should be possible through the factory

**Comment by willayy** [comment]
This US is no longer needed since proejctiles will be instatntiated by AWeapon
