### ISSUE TITLE
US-98: Create Lower Bound For Radius When Finding Player

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#202]
### US-98
As a player I don't want the enemy to be able to move into and on top of me because it makes the gameplay difficult

### Tasks:

- [ ] Introduce a lower bound to the radius search for player in AICommander
- [ ] Update methods that use the search method for this change

### Acceptance Criteria:

- [ ] The enemy entities can't move directly into and on top of the player
