### ISSUE TITLE
US-99: Fix terrain generation bug

### ISSUE THREAD

**Issue by adamkvarnsund** [0-Gixty-0/Grupp-11-OOPP#208]
As a user I never want to get stuck in a water pocket when playing the game

### Because
It makes the game easier to play and can in some cases even make the game playable at all

### Tasks

- [ ] Add the class isMapConnected to the class AdvancedMapGenerator
- [ ] Add Breadth first search for the sea tiles in the map
- [ ] Add check if all sea tiles are visited functionality
- [ ] Add checking neighbour functionality
- [ ] Finish the isMapConnected function by composing it with the added functionality
- [ ] Add tests
- [ ] Add documentation in README
- [ ] Update UML diagram

### Acceptance criteria
There is little to no chance that the map is created with islands that trap the player inside a water pocket
