### ISSUE TITLE
US-108: Change Dependencies on CommandableEntity To ICommandable 

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#228]
### US-108:
There are multiple dependencies directed at the CommandableEntity class. This breaks the dependency inversion principle and should be fixed. Noticably the interface ICommandable has gone unused throughout the codebase, except for when being implemented by CommandableEntity. However, since CommandableEntity implements this interface, references to the class type can be changed to ICommandable.

### Tasks:

- [ ] Fix dependencies in EntitySpawner
- [ ] Fix dependencies in SailingGameApplication
- [ ] Fix dependencies in UProjectileUtility
- [ ] Fix dependencies in ShipBuilder
- [ ] Fix dependencies in AICommander
- [ ] Fix dependencies in affected test classes

### Acceptance Criteria:
Usage of the CommandableEntity class type in other classes no longer breaks the dependency inversion principle.

**Comment by willayy** [comment]
As we discussed we will remove ICommandable instead since the only class that will ever implement it is CommandableEntity which is a top level class.
