### ISSUE TITLE
US-114: Refactor AdvancedMapGenerator

### ISSUE THREAD

**Issue by adamkvarnsund** [0-Gixty-0/Grupp-11-OOPP#240]
As a developer I want the AdvancedMapGenerator class to follow the SRP

### Because
This makes the codebase more extendable and easier to understand

### Tasks

- [ ] Create class CheckTileConnectivity
- [ ] Move connectivity functionality into the created class
- [ ] Create class FractalNoiseGenerator
- [ ] Move fractal noise functionality into created class
- [ ] Join together the new classes into the main generateMap method in AdvancedMapGenerator

### Acceptance criteria
If the program works as it did before this change then it is accepted, this US creates extendability not functionality
