### ISSUE TITLE
US-35 As a developer i want to use a class Matrix instead of ArrayList<ArrayList<>>

### ISSUE THREAD

**Issue by willayy** [0-Gixty-0/Grupp-11-OOPP#43]
### Becasue 
- Its more readable.
- It has a better interface.

### Tasks
- [ ] Create a generic class Matrix<T> or find one in the Java standard library.
- [ ] Make sure it has get(i,j).
- [ ] Make sure it has set(i,j).
- [ ] Make sure it has T getType().
- [ ] Make sure it has Int getSize().
- [ ] Make sure it has Tuple getDimensions().

### Acceptance criteras for tasks.

- [ ] There is a testclass for Matrix.
- [ ] All methods above have a test.
- [ ] All methods do what they are supposed to do (if what they do isnt self explanatory please comment).

### DoD

- All tasks implemented and meet their acceptance criteria.
