### ISSUE TITLE
US-36 As a developer i dont want LocationEntity to be able to have a AMovabelBody

### ISSUE THREAD

**Issue by willayy** [0-Gixty-0/Grupp-11-OOPP#50]
### Because
A location entity is not supposed to have body capable of moving.

### Tasks
- [x] Implement AImmovableBody
- [x] Replace LocationEntity ABody with AImmovableBody

### Acceptance criteria
- [x] All tasks completed
- [x] LocationEntity cant have an AMovableBody

### DoD
- All tasks implemented and meet their acceptance criteria.
