### ISSUE TITLE
US-38: Implement Drawing Player To Map

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#57]
### US-38
As a player I want to be able to see myself on the map in order to play the game.

Implement drawing the player to the map in the view module based on an int matrix representing entities on the screen.

### Tasks

- [x] Refactor abstract class AViewTile
- [x] Create concrete class EntityTile
- [x] Rename ViewTile to TerrainTile
- [x] Override abstract methods from AViewTile in TerrainTile 
- [x] Extend functionality of class GameEntities
- [x] Create method in class GameEntities for creating ViewEntities in a matrix form
- [x] Extend AppWindow to draw ViewEntities to the screen

### Acceptance Criteria

- [x] The player ship is visible on the screen
- [x] The player ship is contained in one tile
- [x] The player ship image is correctly dimensioned

**Comment by 0-Gixty-0** [comment]
Notes:
Used Template Method design pattern in method createImageIcon
