### ISSUE TITLE
US-39: Reduce code duplication for the position attribute

### ISSUE THREAD

**Issue by adamkvarnsund** [0-Gixty-0/Grupp-11-OOPP#60]
As a developer I don't want code duplication

### Tasks

- [ ] Create new abstract class APositionable
- [ ] Make APositionable inherit ATextureIdentifiable
- [ ] Clean up current subclasses (code, comments, tests)

**_Reasoning for inheritance_**

I argue that if the object has a position, it also has a texture ID. But just because an object has a texture ID, it does not mean it has a position. This is just the reasoning behind the decision. In the future I believe all objects will have a position regardless.

### Acceptance criteria

* The code has no code duplication
* It works just as before the implementation but with better abstraction
