### ISSUE TITLE
US-40: Implement Factory Hierarchy For Movable Game Entities

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#66]
### US-40:
As a developer I want to make use of factories when creating movable entities in the game because it makes the code easier to understand and follows “high cohesion, low coupling”

This user story is about creating a hierarchy of classes following the factory design pattern in order to make the process of creating entities, in this case including creating bodies for such entities, more intuitive and automated. This makes the code easier to understand and allows our modules to be usable without having to depend on everything, i.e. high cohesion low coupling. 

I spent a long time deciding on which factory pattern to use. I settled on the standard version and minimized the scope of the user story with intention of later extension.

### Tasks:

- [x] Create an interface for movable entity factories
- [x] Create a concrete factory for making standard movable entities
- [x] Create a method for creating a player in movable entity factory
- [x] Create a method for creating an enemy in movable entity factory

### Acceptance Criteria:

- [ ] A developer can create a player from the factory
- [x] ~~A developer can create an enemy from the factory~~

**Comment by 0-Gixty-0** [comment]
Note:
Currently there is no UnplayableEntity class implemented despite the UML diagram indicating as such. I have therefore decided to remove the acceptance criteria of creating an enemy from the factory and ultimately merging anyways for sake of brevity in development.
