### ISSUE TITLE
US-42: Create Default Constructor For Ship

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#67]
### US-42:
As a developer I want a default constructor for the ship class because it makes creating new objects of that type easier.

I think this is necessary to the codebase because it makes creating objects of that type very easy and simple. If it is not included we risk very long constructor calls and code duplication.

### Tasks:

- [x] Create a default constructor in the Ship class that represents a simple ship

### Acceptance Criteria:

- [x] ~~The default constructor should be default, the one that is specified first when creating new objects of type Ship~~
- [x] The constructor works as intended
