### ISSUE TITLE
US-44 As I developer I want to know what to test and have efficient tests for it.

### ISSUE THREAD

**Issue by willayy** [0-Gixty-0/Grupp-11-OOPP#70]
### Because
Efficiently written tests makes writing further tests easier, and tests by themselves makes development much easier.

### Tasks
- [x] Make a clear definition of what to test (meeting 20/11/2023).
- [x] Remove deprecated tests from the tests package (if there are any).
- [x] Write tests for everything that should have test (according the the new clear definitions).
- [x] Rewrite duplicate tests using parametric testing to ensure efficiency (looking at movement tests specifically).
- [x] Adding another task: Read the Javadoc while looking through all the tests, since many classes has been changed and therefore the Javadoc is inaccurate.  

### Acceptance criteria
There exists a test for everything that should be tested according to the "Arbetsflöde" appendix of the group contract. There are no duplicate tests. There are clear definitions for what should be tested.

### DoD
All tasks finished according to acceptance criteria

**Comment by cavassi** [comment]
Issue continued in #115 because git issues in branch.
