### ISSUE TITLE
US-43: Implement UnplayableEntity Class 

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#77]
### US-43
As a user I want there to be other ships and locations in the world to make the game more interesting to play

User story is about implementing the unplayable entity class and it's implemented interface ai commandable. This in order to allow enemy ships to exist in the game

### Tasks

- [x] Create basic structure and constructor for UnplayableEntity class
- [x] Implement methods inherited from interface
- [x] Connect interface of UnplayableEntity to it's body when possible

### Acceptance Criteria

- [x] It is possible to construct objects of type UnplayableEntity
- [x] All inherited methods are implemented
- [x] All methods that pass down to body are connected to body of entity
