### ISSUE TITLE
US-51: Implement Interface HasWeapon

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#79]
### US-51
As a developer I want to implement an interface for objects having weapons so that other classes can depend on abstractions and not implementations

When implementing the class UnplayableEntity I realized that the attack method needed to check if the body actually has the ability to attack which will be done through some form of weapon. Therefore we need some form of interface for how weapons are to be used and changed. A Ship and a static turret may have different implementations of firing a weapon and may have different weapon types in the future.

### Tasks

- [x] Create HasWeapon interface
- [x] Let Ship Implement HasWeapon
- [x] Refactor class Ship to adhere to the new interface
- [x] ~~Make attackCommand implemented in AMovableEntity instead of subclasses~~
- [x] Implement attackCommand in UnplayableEntity and PlayableEntity

### Acceptance Criteria

- [x] PlayableEntity and UnplayableEntity is not dependent on concrete implementations
- [x] Ship class implements methods from HasWeapon interface
- [x] ~~AMovableEntity is dependent on HasWeapon~~
