### ISSUE TITLE
US-52: Remove Dimensions Parameter From ABody Hierarchy

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#82]
### US-52
As a developer I want to remove the dimensions parameter from the ABody hierarchy because it is confusing and unnecessary to the MVP

This parameter has been an issue in the codebase for some time. It is confusing and not necessary to the code.

### Tasks

- [x] Remove parameter from all constructor signatures
- [x] Remove parameter from all constructor bodies
- [x] Remove parameter from all classes attributes
- [x] Remove parameter from all constructor calls

### Acceptance Criteria

- [x] No warnings or errors in the code regarding dimensions parameter
- [x] Main runs as normal
- [x] Tests run as normal
