### ISSUE TITLE
US-53: Refactor Entity Hierarchy

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#85]
### US-53
As a developer I want to redesign and refactor the Entity class hierarchy in order to reduce code duplication, dependencies on concrete implementations, and make the code more extendable

The reasoning behind this user story is best described in the issue #81. However, in summary the user story is about cleaning up the code and solving multiple issues we have identified in the current structure of the Entity hierarchy. Partly in order to create a better builder class.

### Tasks

- [x] Rename AMovableEntity to CommandableEntity
- [x] Make CommandableEntity no longer abstract
- [x] Make CommandableEntity implement interface ICommandable
- [x] Move the duplicated methods in AMovableEntity subclasses to the CommandableEntity class as concrete implementations
- [x] Remove classes PlayableEntity, UnplayableEntity, and LocationEntity
- [x] Create interface CanInteract
- [x] Rewrite methods in CommandableEntity to depend on CanInteract, HasWeapon, and IMovable
- [x] Update UML diagram

### Acceptance Criteria

- [x] CommandableEntity depends on interfaces
- [x] It is possible to construct objects of type CommandableEntity
- [x] Body of type HasWeapon can receive attack commands from CommandableEntity
- [x] Body which does not have type HasWeapon cannot receive attack commands from CommandableEntity
- [x] Body of type IMovable can receive move commands from CommandableEntity
- [x] Body which does not have type IMovable cannot receive move commands from CommandableEntity
- [x] Body of type CanInteract can receive interact commands from CommandableEntity
- [x] Body which does not have type CanInteract cannot receive interact commands from CommandableEntity
