### ISSUE TITLE
US-54 As a user i want a map that is centered in the game window and a static camera.

### ISSUE THREAD

**Issue by willayy** [0-Gixty-0/Grupp-11-OOPP#87]
### Because
I like the retro "Pokemon" feel it gives the game.

### Tasks

- [x] The view is centered in the Application window.
- [x] The view covers the entire Application window.
- [x] The Application can be played fullscreen or windowed.
- [x] EntityTiles are rendered on top of TerrainTiles.

### Acceptanc criteria
The game CAN be played windowed but it doesnt have to be a good user experience. The view should cover as much of the application window as possible. Since different screens has different sizes i will try to add some kind of frame around the game map so the game looks good even if its a bit too small for the screen its played on. All tasks need to be finished except the last one, i will  close this US even if that one isnt finsihed since it might not be possible with the framework we are using (Swing).
