### ISSUE TITLE
US-34: Implement Application

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#92]
### US-34:
As a developer I want to connect App module to other MVC modules as a group to make the game run.

### Tasks:

- [x] Application creates view
- [x] Application creates controller
- [x] Application creates map / world in model
- [x] Application creates a player
- [x] Connect controller to application
- [x] Connect controller to player movement
- [x] Create game loop in application
- [x] #94

### Acceptance Criteria:

- [x] The user can move the player ship with the keyboard
- [x] The ship texture moves on the screen from the keyboard

**Comment by willayy** [comment]
Adding the prototype i showed you this friday to this branch and merging
